// ─── Kingdom of Historia — Hero Roster ───────────────────────────────────────
// Each hero has a fantasy identity, passive ability, lore, and visual style.
// Passives are cosmetic/flavor — they map to existing avatar IDs so no DB changes needed.

export interface HeroPassive {
  name: string;
  description: string;
  icon: string; // emoji
}

export interface HeroData {
  avatarId: string;
  name: string;
  fullName: string;
  title: string;
  heroClass: string;
  kingdomOrigin: string;
  rarity: 'Common' | 'Rare' | 'Epic' | 'Legendary';
  rarityClass: string;
  crest: string; // emoji symbol
  symbol: string; // another visual symbol representation
  lore: string;
  biography: string;
  personality: string;
  strengths: string;
  weaknesses: string;
  quote: string;
  goal: string;
  passive: HeroPassive;
  colorAccent: string; // Tailwind color class for accent
  borderClass: string;
  bgGradient: string;
  walkingAnim: string; // CSS class for walking personality
  idleAnim: string; // CSS class for idle personality
  victoryAnim: string;
  defeatAnim: string;
}

export const HEROES: HeroData[] = [
  {
    avatarId: 'avatar_1',
    name: 'Sir Aldric',
    fullName: 'Sir Aldric of the Iron Vanguard',
    title: 'The Last Royal Knight',
    heroClass: 'Royal Knight',
    kingdomOrigin: 'Capital Gates of Historia',
    rarity: 'Legendary',
    rarityClass: 'rarity-legendary',
    crest: '🛡️',
    symbol: '⚔️',
    lore: 'Once captain of the King\'s Guard before the Crown of Wisdom disappeared. Rather than seeking glory, he travels to restore peace to Historia.',
    biography: 'Aldric rose from a humble farmhand to the captain of the King\'s Guard after defending Historia against the Dragon Siege of the Third Age. When the Crown of Wisdom shattered, his sworn brothers scattered. Now he is the last true knight, seeking to rebuild the honor of his fallen order.',
    personality: 'Stoic, honorable, and unyielding. He speaks little but his words carry the weight of an anvil.',
    strengths: 'Unbreakable defense, unwavering loyalty, tactical battlefield knowledge.',
    weaknesses: 'Stubborn to a fault, struggles to adapt to modern magical trickery.',
    quote: '"A kingdom survives through wisdom—not war."',
    goal: 'To restore peace to Historia and reforge the King\'s Guard.',
    passive: {
      name: 'Iron Resolve',
      description: 'Earns +2 bonus Royal Gold after 3 consecutive correct answers.',
      icon: '🛡️',
    },
    colorAccent: 'text-amber-400',
    borderClass: 'border-amber-500/60',
    bgGradient: 'from-amber-950/40 to-stone-950/60',
    walkingAnim: 'anim-walk-heavy',
    idleAnim: 'anim-idle-sword-plant',
    victoryAnim: 'anim-victory-raise-sword',
    defeatAnim: 'anim-defeat-smile',
  },
  {
    avatarId: 'avatar_2',
    name: 'Seraphel',
    fullName: 'Seraphel the Archivist',
    title: 'Voice of the Arcane Codex',
    heroClass: 'Arcane Scholar',
    kingdomOrigin: 'Arcane Academy of Oakhaven',
    rarity: 'Epic',
    rarityClass: 'rarity-epic',
    crest: '📚',
    symbol: '📜',
    lore: 'Seraphel memorised the 10,000-volume Library of Historia by age twelve. She now advises the Crown on ancient prophecies.',
    biography: 'Born in the floating spires of the Arcane Academy, Seraphel was a child prodigy who decoded the lost language of the First Scholars. She carries a magical tome that records every event in the kingdom in real-time, making her the ultimate authority on trivia.',
    personality: 'Highly intelligent, slightly arrogant, and obsessively curious.',
    strengths: 'Flawless memory, rapid problem-solving, vast magical knowledge.',
    weaknesses: 'Lacks practical real-world experience, physically frail.',
    quote: '"Every answer is already written — find the page."',
    goal: 'To document every single Relic of Wisdom before they are lost again.',
    passive: {
      name: 'Scholar\'s Edge',
      description: 'Gains +3 seconds on Hard difficulty trials.',
      icon: '📖',
    },
    colorAccent: 'text-purple-400',
    borderClass: 'border-purple-500/60',
    bgGradient: 'from-purple-950/40 to-indigo-950/60',
    walkingAnim: 'anim-walk-float',
    idleAnim: 'anim-idle-read-book',
    victoryAnim: 'anim-victory-magic-burst',
    defeatAnim: 'anim-defeat-drop-book',
  },
  {
    avatarId: 'avatar_3',
    name: 'Thorn Willowmere',
    fullName: 'Thorn of the Elder Trees',
    title: 'Warden of the Emerald Paths',
    heroClass: 'Forest Ranger',
    kingdomOrigin: 'The Whispering Forest',
    rarity: 'Rare',
    rarityClass: 'rarity-rare',
    crest: '🌿',
    symbol: '🏹',
    lore: 'Raised by the Guardians of the Enchanted Forest, Thorn can read the land like a map and knows all of Historia\'s Secret Passages.',
    biography: 'Found abandoned in the Whispering Forest, Thorn was raised by the ancient treants. He serves as the silent protector of the borders, armed with a bow carved from the World Tree. He ventures into the civilised kingdom only to track down corrupted relics.',
    personality: 'Quiet, observant, and deeply connected to nature.',
    strengths: 'Incredible tracking skills, camouflage, unmatched agility.',
    weaknesses: 'Distrustful of machinery and castle-dwellers.',
    quote: '"The forest remembers what men forget."',
    goal: 'To cleanse the kingdom of the cursed magic left by the shattered crown.',
    passive: {
      name: 'Pathfinder',
      description: 'Once per match, ignores a Cursed Rune penalty.',
      icon: '🗺️',
    },
    colorAccent: 'text-emerald-400',
    borderClass: 'border-emerald-500/60',
    bgGradient: 'from-emerald-950/40 to-green-950/60',
    walkingAnim: 'anim-walk-stealth',
    idleAnim: 'anim-idle-look-around',
    victoryAnim: 'anim-victory-bow-flourish',
    defeatAnim: 'anim-defeat-kneel',
  },
  {
    avatarId: 'avatar_4',
    name: 'Mira Ashveil',
    fullName: 'Mira of the Obsidian Court',
    title: 'Phantom of the Shadows',
    heroClass: 'Shadow Rogue',
    kingdomOrigin: 'Underground City of Nox',
    rarity: 'Epic',
    rarityClass: 'rarity-epic',
    crest: '🌑',
    symbol: '🗡️',
    lore: 'No one knows Mira\'s true origin. Her impossible knowledge of secret routes and hidden relics is both revered and feared.',
    biography: 'An orphan trained by the elusive Obsidian Court, Mira is the kingdom\'s greatest spy. She steals not for wealth, but for secrets. She views the quest for the Crown of Wisdom as the ultimate heist.',
    personality: 'Cynical, witty, and fiercely independent.',
    strengths: 'Lockpicking, stealth, quick reflexes.',
    weaknesses: 'Refuses to trust anyone, easily tempted by shiny treasures.',
    quote: '"The shadows know the truth kings dare not speak."',
    goal: 'To steal the Crown of Wisdom before the pompous knights get their hands on it.',
    passive: {
      name: 'Veil Step',
      description: 'Small chance (+15%) to gain +1 movement on any correct answer.',
      icon: '👻',
    },
    colorAccent: 'text-slate-400',
    borderClass: 'border-slate-400/60',
    bgGradient: 'from-slate-900/60 to-zinc-950/70',
    walkingAnim: 'anim-walk-brisk',
    idleAnim: 'anim-idle-toss-coin',
    victoryAnim: 'anim-victory-vanish',
    defeatAnim: 'anim-defeat-smoke-bomb',
  },
  {
    avatarId: 'avatar_5',
    name: 'Caldwyn',
    fullName: 'Lord Caldwyn Lightbringer',
    title: 'Paladin of the Silver Dawn',
    heroClass: 'Noble Paladin',
    kingdomOrigin: 'Sacred Temple of Sol',
    rarity: 'Legendary',
    rarityClass: 'rarity-legendary',
    crest: '☀️',
    symbol: '🛡️',
    lore: 'As the last of the Silver Dawn Order, he carries the blessed sword Luminar and vows to restore the Crown of Wisdom.',
    biography: 'Caldwyn is a paragon of virtue who draws power from the sun itself. After his temple was destroyed by a cursed relic, he swore a blood oath to purge darkness from the realm. He believes the Crown is a divine artifact that must be protected at all costs.',
    personality: 'Self-righteous, deeply devout, and unwavering.',
    strengths: 'Divine protection, inspiring leadership, immense physical strength.',
    weaknesses: 'Overconfident, easily blinded by his own strict moral code.',
    quote: '"Light reveals what darkness conceals."',
    goal: 'To destroy all cursed runes and restore the kingdom\'s divine grace.',
    passive: {
      name: 'Holy Aegis',
      description: 'Shield Relic lasts one extra turn before expiring.',
      icon: '✨',
    },
    colorAccent: 'text-yellow-300',
    borderClass: 'border-yellow-400/60',
    bgGradient: 'from-yellow-950/40 to-amber-950/60',
    walkingAnim: 'anim-walk-proud',
    idleAnim: 'anim-idle-pray',
    victoryAnim: 'anim-victory-sun-beam',
    defeatAnim: 'anim-defeat-shield-break',
  },
  {
    avatarId: 'avatar_6',
    name: 'Vesper Ironquill',
    fullName: 'Vesper Ironquill',
    title: 'Grand Alchemist',
    heroClass: 'Battle Alchemist',
    kingdomOrigin: 'The Obsidian Tower',
    rarity: 'Rare',
    rarityClass: 'rarity-rare',
    crest: '⚗️',
    symbol: '🧪',
    lore: 'Vesper transformed the Tower of Silence into Historia\'s premier alchemical academy, though her experiments often explode.',
    biography: 'A mad genius who treats magic as a measurable science. She was expelled from the Arcane Academy for trying to transmute the dean\'s robes into gold. She now travels the board testing experimental potions on herself.',
    personality: 'Eccentric, manic, and highly enthusiastic about explosions.',
    strengths: 'Brewing potions, unpredictable tactics, vast material knowledge.',
    weaknesses: 'Terrible at planning, prone to self-sabotage via experimental failure.',
    quote: '"Science and sorcery are merely spells with better documentation."',
    goal: 'To discover the ultimate formula for turning common rocks into Royal Gold.',
    passive: {
      name: 'Transmutation',
      description: 'Gains a 10% discount at the Merchant\'s Caravan.',
      icon: '🧪',
    },
    colorAccent: 'text-lime-400',
    borderClass: 'border-lime-500/60',
    bgGradient: 'from-lime-950/40 to-green-950/60',
    walkingAnim: 'anim-walk-skip',
    idleAnim: 'anim-idle-shake-flask',
    victoryAnim: 'anim-victory-potion-drink',
    defeatAnim: 'anim-defeat-explosion',
  },
  {
    avatarId: 'avatar_7',
    name: 'Gareth Cogsworth',
    fullName: 'Gareth Cogsworth III',
    title: 'Master Engineer',
    heroClass: 'Kingdom Engineer',
    kingdomOrigin: 'The Iron Forges of Kord',
    rarity: 'Rare',
    rarityClass: 'rarity-rare',
    crest: '⚙️',
    symbol: '🔧',
    lore: 'Gareth built the Great Clock Tower of Historia. His mechanical dice-rolling contraption is considered cheating by everyone except the King.',
    biography: 'A brilliant dwarven engineer who believes flesh is weak and brass is eternal. He created the mechanical beasts that guard the Royal Treasury and has built a steampunk suit to aid him on his quest.',
    personality: 'Grumpy, practical, and heavily reliant on logic.',
    strengths: 'Mechanical ingenuity, high armor, can repair broken relics.',
    weaknesses: 'Slow, easily frustrated by things that can\'t be fixed with a wrench.',
    quote: '"Every problem is a machine waiting to be understood."',
    goal: 'To reverse-engineer the Crown of Wisdom and build a mechanical duplicate.',
    passive: {
      name: 'Clockwork Precision',
      description: 'Lucky Dice Relic cooldown is reduced by 1 turn.',
      icon: '🔩',
    },
    colorAccent: 'text-cyan-400',
    borderClass: 'border-cyan-500/60',
    bgGradient: 'from-cyan-950/40 to-sky-950/60',
    walkingAnim: 'anim-walk-clunky',
    idleAnim: 'anim-idle-tinker',
    victoryAnim: 'anim-victory-steam-vent',
    defeatAnim: 'anim-defeat-malfunction',
  },
  {
    avatarId: 'avatar_8',
    name: 'Lunara',
    fullName: 'Lunara of the Moonspire',
    title: 'Mystic Oracle',
    heroClass: 'Mystic Oracle',
    kingdomOrigin: 'Moonspire Sanctum',
    rarity: 'Epic',
    rarityClass: 'rarity-epic',
    crest: '🔮',
    symbol: '🌙',
    lore: 'Lunara communes with the Celestial Scribes. She sees not the future, but the shape of questions yet unasked.',
    biography: 'Blind since birth, Lunara sees the world through the flow of magical ley-lines. She has been prophesied to either save the kingdom or doom it, though the Celestial Scribes refuse to clarify which.',
    personality: 'Serene, enigmatic, and often speaks in riddles.',
    strengths: 'Foresight, mind reading, immunity to illusions.',
    weaknesses: 'Physically fragile, easily overwhelmed by loud noises.',
    quote: '"The answer arrives before the question if you know how to listen."',
    goal: 'To fulfill the ancient prophecy of the Moonspire.',
    passive: {
      name: 'Foresight',
      description: 'Earns +5 bonus XP after completing a match.',
      icon: '🌙',
    },
    colorAccent: 'text-indigo-300',
    borderClass: 'border-indigo-400/60',
    bgGradient: 'from-indigo-950/40 to-violet-950/60',
    walkingAnim: 'anim-walk-glide',
    idleAnim: 'anim-idle-levitate',
    victoryAnim: 'anim-victory-moon-glow',
    defeatAnim: 'anim-defeat-fade-away',
  },
  {
    avatarId: 'avatar_9',
    name: 'Ragnar Embervein',
    fullName: 'Ragnar Embervein',
    title: 'Dragon Hunter',
    heroClass: 'Dragon Hunter',
    kingdomOrigin: 'The Ashen Peaks',
    rarity: 'Legendary',
    rarityClass: 'rarity-legendary',
    crest: '🐉',
    symbol: '🔥',
    lore: 'Ragnar has slain seven dragons and made boots from two of them. He claims the Crown is hidden in a dragon hoard.',
    biography: 'A towering barbarian from the harsh northern mountains. He grew bored of fighting dragons because they stopped being a challenge. He joined the quest for the Crown simply because someone told him it was impossible.',
    personality: 'Boisterous, arrogant, and incredibly tough.',
    strengths: 'Immense raw power, high pain tolerance, fearless.',
    weaknesses: 'Reckless, tends to punch traps instead of disarming them.',
    quote: '"If it breathes fire, I\'ve already won. The trick is not burning down the library."',
    goal: 'To find a challenge worthy of his strength.',
    passive: {
      name: 'Dragonhide',
      description: 'Reduces Cursed Rune (Trap) coin penalty by 3 gold.',
      icon: '🔥',
    },
    colorAccent: 'text-red-400',
    borderClass: 'border-red-500/60',
    bgGradient: 'from-red-950/40 to-rose-950/60',
    walkingAnim: 'anim-walk-stomp',
    idleAnim: 'anim-idle-crack-knuckles',
    victoryAnim: 'anim-victory-roar',
    defeatAnim: 'anim-defeat-fall-back',
  },
  {
    avatarId: 'avatar_10',
    name: 'Countess Elara',
    fullName: 'Countess Elara Von Thorne',
    title: 'Royal Tactician',
    heroClass: 'Royal Tactician',
    kingdomOrigin: 'The Iron Banner Estate',
    rarity: 'Epic',
    rarityClass: 'rarity-epic',
    crest: '⚜️',
    symbol: '👑',
    lore: 'Elara commands Historia\'s greatest intelligence network, and she plays board games with ruthless precision.',
    biography: 'A noblewoman who treats every conversation as a chess match. She funded half the expeditions in Historia just to control the information they brought back. She seeks the Crown of Wisdom not to wear it, but to control the one who does.',
    personality: 'Cunning, polite but deadly, always three steps ahead.',
    strengths: 'Master manipulator, endless resources, flawless strategist.',
    weaknesses: 'Arrogant, struggles when faced with unpredictable chaos.',
    quote: '"The battlefield and the board are one — control information, control victory."',
    goal: 'To control the flow of knowledge throughout the entire kingdom.',
    passive: {
      name: 'Grand Strategy',
      description: 'Coin Multiplier Relic yields +2 bonus gold on activation.',
      icon: '📜',
    },
    colorAccent: 'text-rose-400',
    borderClass: 'border-rose-500/60',
    bgGradient: 'from-rose-950/40 to-pink-950/60',
    walkingAnim: 'anim-walk-elegant',
    idleAnim: 'anim-idle-sip-tea',
    victoryAnim: 'anim-victory-smirk',
    defeatAnim: 'anim-defeat-scowl',
  },
];

export function getHeroByAvatarId(avatarId: string): HeroData | undefined {
  return HEROES.find(h => h.avatarId === avatarId);
}

// ─── Fantasy vocabulary replacements ─────────────────────────────────────────
export const FANTASY_LABELS = {
  // UI Labels
  lobby: 'Great Hall',
  shop: "Merchant's Caravan",
  achievements: 'Royal Honours',
  matchHistory: 'Chronicles',
  leaderboard: 'Hall of Legends',
  coins: 'Royal Gold',
  powerups: 'Relics',
  victory: 'Crowned Champion',
  ready: "Answer the King's Call",
  matchStart: 'The Quest Begins',
  // Tile Names
  mysteryTile: 'Ancient Relic',
  trapTile: 'Cursed Rune',
  bonusTile: 'Blessing Shrine',
  treasureTile: 'Royal Treasury',
  shortcutTile: 'Secret Passage',
  challengeTile: "Knight's Trial",
  wildTile: 'Fate Scroll',
  // Flavor messages
  flavorMessages: [
    'The castle bells echo across Historia…',
    'A forgotten relic awakens.',
    "The King's blessing smiles upon you.",
    'The Royal Librarians present another trial.',
    'A hidden passage has been discovered.',
    'The ancient spirits guide your journey.',
    'Wisdom lights your path.',
    'The royal vault reveals its treasures.',
    'Brave heroes never falter in Historia.',
    'The Crown of Wisdom awaits the worthy.',
    'Scholars of old watch from the library walls.',
    'The grand banners of Historia wave in your honour.',
    'A legend is born in the Kingdom of Historia.',
    'The ancient trials demand your best answers.',
    'Your name shall be written in the Chronicles.',
  ],
};

export function getRandomFlavorMessage(): string {
  const msgs = FANTASY_LABELS.flavorMessages;
  return msgs[Math.floor(Math.random() * msgs.length)];
}
